### ISSUE TITLE
MVP OUTLINE

### ISSUE THREAD

**Issue by meltonlogan615** [meltonlogan615/FuzzyBuddies#2]
# PHASE I
- [ ] Browse Fuzzy Buddies Available For Adoption
- [ ] Filter By Species
- [ ] Filter By Distance
- [ ] Display Fuzzy Buddy Details
- [ ] Display Adoption Agency Contact Info
- [ ] Share Fuzzy Buddy via Share Sheet
- [ ] No UnFuzzy Buddy Access to Edit or Delete Data, GET only

# PHASE II
- [ ] Account Creation (Sign In with Apple & FireBase)
- [ ] Favorite / Bookmark Fuzzy Buddies
- [ ] If available, Complete Adoption Papers within App
- [ ] Filter by Breed, Size

# PHASE III
- [ ] Adoption Success Stories
- - [ ] Photos of Adopted Fuzzy Buddies (Anonymous Posting)
